### ISSUE TITLE
Request for Fabric Loader 0.16.0 - 1.21 Compatibility

### ISSUE THREAD

**Issue by MrCookie112** [Enchanted-Games/block-place-particles#12]
Hello,

First of all, I'd like to thank you for your superb mod. However, I've noticed that the mod currently only works with the latest version of Fabric Loader and that many other mods are not compatible with it. This makes it difficult for me to take advantage of your mod.

Would it be possible to add support for Fabric Loader 0.16.0-1.21? This would be much appreciated by users like me who depend on an older version for the compatibility of their other mods.

**Comment by Enchanted-Games** [comment]
just uploaded a new version to modrinth (v0.3.1) that will load fabric loader 0.16.0 and up.
in github releases, i removed v0.3 for fabric and replaced it with v0.3.1
