### ISSUE TITLE
[Bug] Unable to Access Mod Settings via Mod Menu (Fabric Loader 0.16.0 - 1.21)

### ISSUE THREAD

**Issue by MrCookie112** [Enchanted-Games/block-place-particles#13]
**Describe the bug**

Hello,

First of all, thank you for your work on this mod. However, I’ve noticed that it’s currently impossible to access the mod configuration through the Mod Menu. This limits the ability to adjust settings directly in-game.

Would it be possible to fix this issue to make the configuration options accessible from the Mod Menu?

Thank you in advance for your attention and support.

**To Reproduce**  

1. Install the mod "Particle Interactions" along with all its dependencies and the Mod Menu.
2. Go to the Mod Menu and click on the settings for the mod "Particle Interactions."
3. An error occurs, blocking access and displaying red text.

**Expected behaviour**
I expected to access the configuration settings for the "Particle Interactions" mod through the Mod Menu.

**Additional content**
![image](https://github.com/user-attachments/assets/6f318cf9-dfd2-468b-b654-2aebeec0e604)

**Environment**
 - Mod Version: v0.3.1
 - Mod Loader: fabric
 - Mod Loader Version: 1.21 (0.16.0)
 - Fabric Api Version: 0.102.0

**Comment by Enchanted-Games** [comment]
thanks for the report! this seems to be something that changed in yacl 3.6.x.
as a temporary workaround you can install yet another config lib 3.5.0

**Comment by Enchanted-Games** [comment]
should be fixed in 0.3.2
