### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Daniel99j2** [Enchanted-Games/block-place-particles#14]
**Describe the bug**
The config does not apply in-game, and the config screen has an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Mods
2. Click on Particle Interactions

**Expected behaviour**
It works

**Additional content**
![image](https://github.com/user-attachments/assets/cdd654ad-47b6-4b8a-874a-2235e2f62d03)

[16:26:33] [Render thread/ERROR]: Error from mod 'eg_particle_interactions'
--
5944 | java.lang.IllegalArgumentException: Cannot build label option without a state manager or lines
5945 | at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[axiom.jar:?]
5946 | at dev.isxander.yacl3.impl.LabelOptionImpl$BuilderImpl.build(LabelOptionImpl.java:83) ~[YetAnotherConfigLib-3.6.1+1.21-fabric.jar:?]
5947 | at games.enchanted.blockplaceparticles.config.ConfigScreen.createConfigCategories(ConfigScreen.java:67) ~[eg_particle_interactions-0.3-fabric-mc1.21.1.jar:?]
5948 | at games.enchanted.blockplaceparticles.config.ConfigScreen.createConfigScreen(ConfigScreen.java:27) ~[eg_particle_interactions-0.3-fabric-mc1.21.1.jar:?]
5949 | at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:70) ~[modmenu-11.0.3.jar:?]
5950 | at com.terraformersmc.modmenu.gui.ModsScreen.safelyOpenConfigScreen(ModsScreen.java:644) ~[modmenu-11.0.3.jar:?]
5951 | at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:182) ~[modmenu-11.0.3.jar:?]
5952 | at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:172) ~[modmenu-11.0.3.jar:?]
5953 | at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:294) ~[modmenu-11.0.3.jar:?]
5954 | at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
5955 | at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
5956 | at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
5957 | at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
5958 | at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
5959 | at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
5960 | at net.minecraft.class_312.redirect$mam001$viafabricplus$storeEvent(class_312.java:10557) ~[client-intermediary.jar:?]
5961 | at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
5962 | at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.3.jar:?]
5963 | at com.moulberry.flashback.editor.ui.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:233) ~[flashback-0.11.0.jar:?]
5964 | at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.3.jar:?]
5965 | at com.moulberry.axiom.editor.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:217) ~[axiom.jar:?]
5966 | at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
5967 | at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
5968 | at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
5969 | at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
5970 | at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
5971 | at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
5972 | at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
5973 | at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
5974 | at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
5975 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
5976 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
5977 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]

**Environment**
 - Mod Version: 0.3.1
 - Mod Loader: Fabric
 - Mod Loader Version: 1.21

**Comment by Daniel99j2** [comment]
oops

**Comment by Daniel99j2** [comment]
fixed

**Comment by Enchanted-Games** [comment]
Update the mod to v0.3.2

**Comment by Daniel99j2** [comment]
That fixed it! Thanks!
