### ISSUE TITLE
Cant disable all generic block placing particles

### ISSUE THREAD

**Issue by SvveetMavis** [Enchanted-Games/block-place-particles#18]
I only want particles for the blocks specified in the override tab but instead its giving it to all the blocks, where would I change that

**Comment by Enchanted-Games** [comment]
at the bottom of the block particle overrides tab, you can set the amount of vanilla particles to spawn on block placed to 0

**Comment by SvveetMavis** [comment]
oh, thank you, i was over complicating it i guess lol
