### ISSUE TITLE
[Feature Request] Seperate bubbles from placing particles

### ISSUE THREAD

**Issue by SvveetMavis** [Enchanted-Games/block-place-particles#9]
I think the bubbles from placing something underwater should be a separate config option to just the generic block placing option because I want the placing bubbles but don't want the normal placing particles for all blocks

**Comment by Enchanted-Games** [comment]
The bubbles should be either enabled or disabled for all blocks, regardless of any block specific particle options. Is this what you are describing or is there something else happening instead?
